"""Editorial batch for knowledge-v52: densify Spanish writing sources.

Summaries are original Editados notes that point to a work; they do not copy
dictionary articles. English craft manuals are left as they are.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any

from app.knowledge.snapshot_data import load_knowledge_seed_snapshot

VERSION = "knowledge-v52"
PUBLISHED_AT = "2026-08-16T15:00:00+00:00"
CREATED_AT = "2026-08-16"
AUTHOR = "minicerebro-seed"
BASE_VERSION = "knowledge-v51"

NEW_SOURCES = [
    {
        "id": "moliner-due",
        "catalog_id": "F027",
        "name": "Diccionario de uso del espanol",
        "responsible": "Maria Moliner",
        "source_type": "diccionario de uso",
        "domains": ["lexico", "uso", "matiz", "definicion orientada al empleo"],
        "authority_level": 5,
        "priority": 2,
        "status": "registered",
        "edition": "pendiente de identificacion",
        "publication_date": "pendiente de identificacion",
        "location": "pendiente de adquisicion",
        "acquisition_status": "available",
        "validation_status": "validated",
        "rights": "referencia bibliografica registrada; contenido no citado extensamente",
        "structure": ["pendiente de estructuracion"],
        "locator_system": ["edicion", "parte", "capitulo", "seccion", "pagina", "entrada", "url"],
    },
    {
        "id": "seco-dudas",
        "catalog_id": "F028",
        "name": "Diccionario de dudas y dificultades de la lengua espanola",
        "responsible": "Manuel Seco",
        "source_type": "diccionario de dudas",
        "domains": ["dudas", "regimen", "construccion", "uso culto"],
        "authority_level": 5,
        "priority": 2,
        "status": "registered",
        "edition": "pendiente de identificacion",
        "publication_date": "pendiente de identificacion",
        "location": "pendiente de adquisicion",
        "acquisition_status": "available",
        "validation_status": "validated",
        "rights": "referencia bibliografica registrada; contenido no citado extensamente",
        "structure": ["pendiente de estructuracion"],
        "locator_system": ["edicion", "parte", "capitulo", "seccion", "pagina", "entrada", "url"],
    },
]

NEW_EDITIONS = [
    {
        "id": "moliner-due:edicion-referencia",
        "source_id": "moliner-due",
        "title": "Diccionario de uso del espanol",
        "edition_label": "edicion de referencia",
        "publication_year": "2007",
        "publisher": "Gredos",
        "isbn": "pendiente",
        "language": "es",
        "format": "print",
        "access_location": "registro bibliografico",
        "rights_status": "referencia bibliografica registrada; contenido no citado extensamente",
        "status": "available",
        "notes": "Edicion de referencia para fichas de uso, no para cita extensa.",
        "created_at": CREATED_AT,
        "updated_at": PUBLISHED_AT,
        "label": "edicion de referencia",
        "publication_date": "2007",
        "location": "registro bibliografico",
        "acquisition_status": "available",
        "validation_status": "validated",
        "rights": "referencia bibliografica registrada; contenido no citado extensamente",
        "structure": ["entradas", "acepciones", "ejemplos"],
        "locator_system": ["edicion", "entrada", "acepcion"],
    },
    {
        "id": "seco-dudas:edicion-referencia",
        "source_id": "seco-dudas",
        "title": "Diccionario de dudas y dificultades de la lengua espanola",
        "edition_label": "edicion de referencia",
        "publication_year": "2011",
        "publisher": "Espasa",
        "isbn": "pendiente",
        "language": "es",
        "format": "print",
        "access_location": "registro bibliografico",
        "rights_status": "referencia bibliografica registrada; contenido no citado extensamente",
        "status": "available",
        "notes": "Edicion de referencia para dudas de construccion.",
        "created_at": CREATED_AT,
        "updated_at": PUBLISHED_AT,
        "label": "edicion de referencia",
        "publication_date": "2011",
        "location": "registro bibliografico",
        "acquisition_status": "available",
        "validation_status": "validated",
        "rights": "referencia bibliografica registrada; contenido no citado extensamente",
        "structure": ["entradas", "dudas", "construcciones"],
        "locator_system": ["edicion", "entrada", "seccion"],
    },
    {
        "id": "moliner-due:pending-edition",
        "source_id": "moliner-due",
        "title": "Diccionario de uso del espanol",
        "edition_label": "pendiente de identificacion",
        "publication_year": "pendiente de identificacion",
        "publisher": "Maria Moliner",
        "isbn": "pendiente de identificacion",
        "language": "es",
        "format": "pendiente de identificacion",
        "access_location": "pendiente de adquisicion",
        "rights_status": "referencia bibliografica registrada; contenido no citado extensamente",
        "status": "registered",
        "notes": "edicion pendiente de registro bibliografico",
        "created_at": CREATED_AT,
        "updated_at": CREATED_AT,
        "label": "pendiente de identificacion",
        "publication_date": "pendiente de identificacion",
        "location": "pendiente de adquisicion",
        "acquisition_status": "available",
        "validation_status": "validated",
        "rights": "referencia bibliografica registrada; contenido no citado extensamente",
        "structure": ["pendiente de estructuracion"],
        "locator_system": ["edicion", "parte", "capitulo", "seccion", "pagina", "entrada", "url"],
    },
    {
        "id": "seco-dudas:pending-edition",
        "source_id": "seco-dudas",
        "title": "Diccionario de dudas y dificultades de la lengua espanola",
        "edition_label": "pendiente de identificacion",
        "publication_year": "pendiente de identificacion",
        "publisher": "Manuel Seco",
        "isbn": "pendiente de identificacion",
        "language": "es",
        "format": "pendiente de identificacion",
        "access_location": "pendiente de adquisicion",
        "rights_status": "referencia bibliografica registrada; contenido no citado extensamente",
        "status": "registered",
        "notes": "edicion pendiente de registro bibliografico",
        "created_at": CREATED_AT,
        "updated_at": CREATED_AT,
        "label": "pendiente de identificacion",
        "publication_date": "pendiente de identificacion",
        "location": "pendiente de adquisicion",
        "acquisition_status": "available",
        "validation_status": "validated",
        "rights": "referencia bibliografica registrada; contenido no citado extensamente",
        "structure": ["pendiente de estructuracion"],
        "locator_system": ["edicion", "parte", "capitulo", "seccion", "pagina", "entrada", "url"],
    },
]

def _unit(
    source_id: str,
    edition_id: str,
    slug: str,
    name: str,
    card_type: str,
    branch: tuple[str, str],
    *,
    aliases: list[str],
    section: str,
    definition: str,
    statement: str,
    excerpt: str,
    signals: list[str],
    risks: list[str],
    contexts: list[str],
    node_type: str = "norma",
    claim_type: str = "usage",
    domain: str = "grammar.usage",
) -> dict[str, Any]:
    return {
        "source_id": source_id,
        "edition_id": edition_id,
        "slug": slug,
        "name": name,
        "card_type": card_type,
        "branch": branch,
        "aliases": aliases,
        "section": section,
        "definition": definition,
        "statement": statement,
        "excerpt": excerpt,
        "signals": signals,
        "risks": risks,
        "contexts": contexts,
        "node_type": node_type,
        "claim_type": claim_type,
        "domain": domain,
    }


UNITS = [
    _unit(
        "rae-dpd",
        "rae-dpd:edicion-2005",
        "leismo-laismo-loismo",
        "Leismo, laismo y loismo",
        "grammar_usage",
        ("gramatica", "pronombres"),
        aliases=["leismo", "laismo", "loismo", "pronombre atono"],
        section="leismo, laismo y loismo",
        definition="Criterio para elegir le, la o lo segun funcion y zona, sin copiar el habla local al texto general.",
        statement="La revision de le, la y lo exige distinguir la funcion del pronombre y no imponer un leismo de zona al registro general.",
        excerpt="Resumen editorial: el sistema panhispanico distingue funciones; el leismo de persona puede ser culto en algunos casos, el laismo y el loismo no se recomiendan en la prosa general.",
        signals=["le dije", "la dije", "lo di un libro", "le vi"],
        risks=["corregir por dialecto propio sin mirar la funcion"],
        contexts=["revision gramatical", "edicion", "prosa general"],
    ),
    _unit(
        "rae-dpd",
        "rae-dpd:edicion-2005",
        "porque-por-que",
        "Porque, por que, porqué y por que",
        "grammar_usage",
        ("gramatica", "grafia"),
        aliases=["porque", "por que", "porqué", "por que relativo"],
        section="porque / por que / porqué",
        definition="Criterio para no mezclar causa, pregunta, sustantivo y relativo con la secuencia por + que.",
        statement="La grafia de por y que depende de si introduce causa, interrogacion, un nombre o un relativo con antecedente.",
        excerpt="Resumen editorial: porque causal va junto; por que interrogativo o exclamativo va separado; el porqué sustantivo lleva articulo; el relativo por que mantiene la preposicion y el que.",
        signals=["porque", "por que", "el porqué", "el motivo por que"],
        risks=["tildar por costumbre o juntar en preguntas"],
        contexts=["correccion", "ensayo", "edicion"],
    ),
    _unit(
        "rae-dpd",
        "rae-dpd:edicion-2005",
        "sino-si-no",
        "Sino y si no",
        "grammar_usage",
        ("gramatica", "nexos"),
        aliases=["sino", "si no", "contraposicion"],
        section="sino / si no",
        definition="Criterio para separar la contraposicion sino de la condicion si no.",
        statement="Sino contrapone despues de una negacion; si no introduce una condicion negativa y admite pausa o complemento.",
        excerpt="Resumen editorial: si la secuencia equivale a 'en caso de que no' va separada; si equivale a 'mas bien / excepto' va junta.",
        signals=["no esto sino", "si no llueve", "no solo sino tambien"],
        risks=["juntar la condicion o separar la contraposicion"],
        contexts=["correccion", "argumentacion"],
    ),
    _unit(
        "rae-dpd",
        "rae-dpd:edicion-2005",
        "haber-impersonal",
        "Haber impersonal",
        "grammar_usage",
        ("gramatica", "verbos"),
        aliases=["haber", "habian", "hubieron", "impersonal"],
        section="haber impersonal",
        definition="Criterio para dejar haber existencial en tercera del singular aunque el complemento vaya en plural.",
        statement="En la prosa general, el haber de existencia no concuerda con lo que hay: se escribe habia muchos, no habian muchos.",
        excerpt="Resumen editorial: el cuantificador que sigue es complemento, no sujeto; la concordancia en plural es frecuente en el habla y se revisa en registro cuidado.",
        signals=["habian muchos", "hubieron problemas", "habemos"],
        risks=["imponer el plural por analogia con estar"],
        contexts=["revision gramatical", "edicion"],
    ),
    _unit(
        "rae-dpd",
        "rae-dpd:edicion-2005",
        "gerundio-de-posterioridad",
        "Gerundio de posterioridad",
        "grammar_usage",
        ("gramatica", "gerundio"),
        aliases=["gerundio", "posterioridad", "gerundio de relato"],
        section="gerundio",
        definition="Criterio para no usar el gerundio como simple 'y despues' cuando la accion no es simultanea ni de manera.",
        statement="El gerundio de relato no debe empujar una accion posterior como si fuera concomitante; si hay secuencia, conviene un verbo finito o un nexo temporal.",
        excerpt="Resumen editorial: el gerundio cubre manera, simultaneidad o causa inmediata; la posterioridad neta ('firmo el contrato, marchandose al dia siguiente') se reescribe.",
        signals=["firmando despues", "muriendo al dia", "gerundio de desenlace"],
        risks=["cazar todos los gerundios, incluso los de manera"],
        contexts=["narrativa", "edicion", "revision gramatical"],
    ),
    _unit(
        "rae-dpd",
        "rae-dpd:edicion-2005",
        "donde-adonde",
        "Donde y adonde",
        "grammar_usage",
        ("gramatica", "adverbios"),
        aliases=["donde", "adonde", "a donde"],
        section="donde / adonde",
        definition="Criterio para marcar destino con a cuando el verbo implica movimiento hacia un lugar.",
        statement="Donde localiza; adonde o a donde senala destino. La confusion borra si alguien esta o si se dirige.",
        excerpt="Resumen editorial: con verbos de movimiento el destino lleva a; la localizacion estatica no.",
        signals=["voy donde", "adonde vas", "esta adonde"],
        risks=["anadir a por sistema en verbos de estado"],
        contexts=["correccion", "prosa general"],
    ),
    _unit(
        "rae-dpd",
        "rae-dpd:edicion-2005",
        "mismo-enfatico",
        "Mismo enfatico",
        "grammar_usage",
        ("gramatica", "enfasis"),
        aliases=["el mismo", "la misma", "enfasis innecesario"],
        section="mismo",
        definition="Criterio para quitar el mismo de relleno cuando no identifica ni enfatiza con provecho.",
        statement="Mismo solo se sostiene si identifica o contrapone; como muleta ('el director mismo dijo') suele sobrar.",
        excerpt="Resumen editorial: el uso anafórico de mismo es util; el enfatico vacio hincha la frase sin anadir dato.",
        signals=["el mismo dijo", "en el mismo", "de por si mismo"],
        risks=["borrar un mismo contrastivo necesario"],
        contexts=["estilo", "edicion"],
    ),
    _unit(
        "rae-dpd",
        "rae-dpd:edicion-2005",
        "hasta-que-no",
        "Hasta que no",
        "grammar_usage",
        ("gramatica", "nexos"),
        aliases=["hasta que no", "expletivo no"],
        section="hasta que",
        definition="Criterio para revisar el no expletivo con hasta que cuando la negacion no aporta sentido.",
        statement="Hasta que marca el limite; el no expletivo ('hasta que no venga') es frecuente y en prosa cuidada suele sobrar.",
        excerpt="Resumen editorial: si la negacion no invierte el limite, el texto gana con hasta que venga.",
        signals=["hasta que no", "no hasta que"],
        risks=["quitar un no realmente negativo"],
        contexts=["edicion", "prosa general"],
    ),
    _unit(
        "rae-dpd",
        "rae-dpd:edicion-2005",
        "deber-de-deber",
        "Deber y deber de",
        "grammar_usage",
        ("gramatica", "perifrasis"),
        aliases=["deber de", "obligacion", "conjetura"],
        section="deber / deber de",
        definition="Criterio para no mezclar obligacion y conjetura en deber y deber de.",
        statement="Deber + infinitivo senala obligacion; deber de + infinitivo senala probabilidad. En la duda, la prosa clara elige otra formula.",
        excerpt="Resumen editorial: la frontera se ha relajado en el uso; en edicion conviene no dejar una conjetura escrita como mandato.",
        signals=["debe de ser", "debe terminar", "deberia de"],
        risks=["imponer la distincion donde el contexto ya es claro"],
        contexts=["edicion", "revision gramatical"],
    ),
    _unit(
        "rae-dpd",
        "rae-dpd:edicion-2005",
        "cuantificador-haber-todo",
        "Concordancia de todo y haber",
        "grammar_usage",
        ("gramatica", "concordancia"),
        aliases=["todo", "todos", "cuantificador"],
        section="todo",
        definition="Criterio para que todo concuerde con el sustantivo y no flote como muletilla.",
        statement="Todo concuerda en genero y numero con lo que cuantifica; como adverbio no debe arrastrar un plural fantasma.",
        excerpt="Resumen editorial: la duda frecuente mezcla todo el mundo, todos y el haber existencial; se revisa cada uno por su funcion.",
        signals=["todos el mundo", "todo los datos"],
        risks=["forzar concordancia adverbial"],
        contexts=["correccion"],
    ),
    # DLE
    _unit(
        "rae-dle",
        "rae-dle:edicion-23-digital",
        "acepcion-en-contexto",
        "Acepcion en contexto",
        "lexical_usage",
        ("lexico", "diccionario"),
        aliases=["acepcion", "sentido", "entrada de diccionario"],
        section="uso de acepciones",
        definition="Criterio para elegir la acepcion que el entorno admite, no la primera del articulo.",
        statement="Una palabra precisa es la que encaja en esa frase; el diccionario ordena sentidos, no impone el primero al borrador.",
        excerpt="Resumen editorial: el DLE sirve para comprobar si un sentido existe y con que marcas; no para sustituir el oido del texto.",
        signals=["primera acepcion", "sentido forzado", "palabra culta fuera de sitio"],
        risks=["cambiar a un sinonimo 'mas diccionario' que rompe el registro"],
        contexts=["lexico", "revision"],
        node_type="metodo",
        claim_type="lexical",
        domain="lexicon.usage",
    ),
    _unit(
        "rae-dle",
        "rae-dle:edicion-23-digital",
        "marca-de-registro-diccionario",
        "Marcas de registro del diccionario",
        "lexical_usage",
        ("lexico", "registro"),
        aliases=["coloquial", "desusado", "culto", "marca lexicografica"],
        section="marcas de uso",
        definition="Criterio para leer las marcas de registro antes de copiar una palabra al texto.",
        statement="Una marca de coloquial, desusado o especializado avisa de que la palabra puede chocar con el lector previsto.",
        excerpt="Resumen editorial: el diccionario no prohibe; senala ambito. La edicion decide si ese ambito es el del texto.",
        signals=["desusado", "malsonante", "tecnico en prosa general"],
        risks=["censurar un coloquialismo buscado"],
        contexts=["lexico", "tono"],
        node_type="metodo",
        claim_type="lexical",
        domain="lexicon.register",
    ),
    _unit(
        "rae-dle",
        "rae-dle:edicion-23-digital",
        "locucion-vs-palabra",
        "Locucion frente a palabra suelta",
        "lexical_usage",
        ("lexico", "locuciones"),
        aliases=["locucion", "unidad fraseologica"],
        section="locuciones",
        definition="Criterio para no deshacer una locucion como si fueran piezas independientes.",
        statement="Si el sentido vive en el conjunto, no se sustituye una pieza por sinonimo; se cambia la locucion entera o se deja.",
        excerpt="Resumen editorial: el diccionario recoge locuciones como unidades; romperlas produce calcos y rarezas.",
        signals=["dar cuenta", "caer en la cuenta", "poner en tela de juicio"],
        risks=["inventar una locucion 'mas original'"],
        contexts=["lexico", "edicion"],
        node_type="norma",
        claim_type="lexical",
        domain="lexicon.usage",
    ),
    _unit(
        "rae-dle",
        "rae-dle:edicion-23-digital",
        "prestamo-adaptado",
        "Prestamo adaptado o crudo",
        "lexical_usage",
        ("lexico", "prestamos"),
        aliases=["prestamo", "extranjerismo", "adaptacion grafica"],
        section="extranjerismos",
        definition="Criterio para preferir la forma adaptada cuando el diccionario ya la asienta, salvo cita o voz de personaje.",
        statement="Si hay forma espanola asentada, la prosa general no necesita el prestamo crudo; el crudo se reserva a voz, marca o imposibilidad de calco.",
        excerpt="Resumen editorial: el DLE documenta adaptaciones; la edicion elige entre transparencia para el lector y color del original.",
        signals=["email", "correo", "link", "enlace"],
        risks=["traducir marcas o nombres propios"],
        contexts=["lexico", "estilo editorial"],
        node_type="norma",
        claim_type="lexical",
        domain="lexicon.usage",
    ),
    _unit(
        "rae-dle",
        "rae-dle:edicion-23-digital",
        "plural-de-prestamos",
        "Plural de prestamos",
        "lexical_usage",
        ("lexico", "morfologia"),
        aliases=["plural", "prestamos", "latinismos"],
        section="plural",
        definition="Criterio para formar el plural de prestamos con la grafia que el uso espanol ya sostiene.",
        statement="El plural no se copia del idioma de origen si el espanol ya tiene forma estable; se evita el apostrofo ingles.",
        excerpt="Resumen editorial: la duda frecuente mezcla -s, -es y plurales etimologicos; la edicion elige la forma mas transparente para el lector.",
        signals=["curriculums", "curricula", "mails"],
        risks=["imponer un latinismo de escuela en un aviso"],
        contexts=["correccion", "edicion"],
        node_type="norma",
        claim_type="lexical",
        domain="lexicon.usage",
    ),
    # GTG
    _unit(
        "rae-gtg",
        "rae-gtg:edicion-2019",
        "oracion-y-enunciado",
        "Oracion y enunciado",
        "grammar_concept",
        ("gramatica", "unidades"),
        aliases=["oracion", "enunciado", "frase"],
        section="oracion / enunciado",
        definition="Criterio para no llamar oracion a cualquier tramo entre puntos.",
        statement="El enunciado es la unidad de uso; la oracion es una estructura predicativa. Confundirlas lleva a cortar o unir mal.",
        excerpt="Resumen editorial: el glosario distingue unidad gramatical y unidad comunicativa; la edicion se pregunta que hace el tramo, no solo donde cae el punto.",
        signals=["frase", "oracion incompleta", "punto y seguido"],
        risks=["exigir sujeto explicito en cada enunciado"],
        contexts=["revision gramatical", "taller"],
        node_type="concepto",
        claim_type="grammatical",
        domain="grammar.theory",
    ),
    _unit(
        "rae-gtg",
        "rae-gtg:edicion-2019",
        "deixis",
        "Deixis",
        "grammar_concept",
        ("gramatica", "referencia"),
        aliases=["deixis", "este", "aqui", "ahora"],
        section="deixis",
        definition="Criterio para anclar este, aqui y ahora al lector, no al escritorio del autor.",
        statement="Un deictico sin ancla obliga al lector a adivinar el origen; se sustituye por dato o se fija el origen.",
        excerpt="Resumen editorial: la deixis senala desde un centro. Si el texto cambia de centro sin aviso, el lector se pierde.",
        signals=["este tema", "aqui", "ahora mismo", "eso"],
        risks=["eliminar deicticos vivos de un dialogo"],
        contexts=["claridad", "revision"],
        node_type="concepto",
        claim_type="grammatical",
        domain="grammar.theory",
    ),
    _unit(
        "rae-gtg",
        "rae-gtg:edicion-2019",
        "anafora-cohesion",
        "Anafora y cohesion",
        "grammar_concept",
        ("gramatica", "cohesion"),
        aliases=["anafora", "cohesion", "pronombre"],
        section="anafora",
        definition="Criterio para que el pronombre recupere un antecedente unico y cercano.",
        statement="Si esto, ello o el puede referirse a dos nombres, la cohesion se rompe; se nombra de nuevo o se reordena.",
        excerpt="Resumen editorial: la anafora ahorra repeticion solo cuando el antecedente no compite. En caso de duda, se repite el nombre.",
        signals=["esto", "ello", "dicho", "el mismo"],
        risks=["repetir el nombre hasta el cansancio"],
        contexts=["coherencia", "edicion"],
        node_type="metodo",
        claim_type="grammatical",
        domain="grammar.theory",
    ),
    _unit(
        "rae-gtg",
        "rae-gtg:edicion-2019",
        "perifrasis-verbal",
        "Perifrasis verbal",
        "grammar_concept",
        ("gramatica", "verbo"),
        aliases=["perifrasis", "ir a", "estar gerundio", "tener que"],
        section="perifrasis verbal",
        definition="Criterio para no apilar perifrasis que diluyen el verbo de accion.",
        statement="Una perifrasis aporta aspecto o modalidad; dos o tres seguidas suelen esconder un verbo mas simple.",
        excerpt="Resumen editorial: el glosario trata la perifrasis como unidad; la edicion pregunta si el matiz hace falta o si el verbo simple basta.",
        signals=["va a empezar a", "se encuentra siendo", "tiene que haber que"],
        risks=["aplastar un matiz aspectual buscado"],
        contexts=["estilo", "revision gramatical"],
        node_type="concepto",
        claim_type="grammatical",
        domain="grammar.theory",
    ),
    _unit(
        "rae-gtg",
        "rae-gtg:edicion-2019",
        "modalidad-oracional",
        "Modalidad oracional",
        "grammar_concept",
        ("gramatica", "modalidad"),
        aliases=["enunciativa", "interrogativa", "exhortativa"],
        section="modalidad",
        definition="Criterio para que la puntuacion y el verbo coincidan con lo que el texto pide al lector.",
        statement="Si el tramo pregunta, manda o afirma, la modalidad se ve en el verbo y en los signos; mezclarlos produce un tono falso.",
        excerpt="Resumen editorial: la modalidad no es adorno. Un aviso escrito como pregunta retorica cansa; una orden escrita como duda no se cumple.",
        signals=["¿no crees que", "deberia considerarse", "se ruega"],
        risks=["convertir toda duda en punto"],
        contexts=["tono", "textos para enviar"],
        node_type="concepto",
        claim_type="grammatical",
        domain="grammar.theory",
    ),
    _unit(
        "rae-gtg",
        "rae-gtg:edicion-2019",
        "elipsis-controlada",
        "Elipsis controlada",
        "grammar_concept",
        ("gramatica", "elipsis"),
        aliases=["elipsis", "omitir verbo"],
        section="elipsis",
        definition="Criterio para omitir solo lo que el lector reconstruye sin esfuerzo.",
        statement="La elipsis aligera cuando el material omitido esta a la vista; si hay que adivinar el verbo o el objeto, se restaura.",
        excerpt="Resumen editorial: el glosario describe la elipsis como mecanismo regular. En edicion se prueba leyendo en voz alta el hueco.",
        signals=["y tambien los", "como los anteriores", "verbo omitido"],
        risks=["rellenar elipses ritmicas de un dialogo"],
        contexts=["claridad", "estilo"],
        node_type="metodo",
        claim_type="grammatical",
        domain="grammar.theory",
    ),
    # NGLE extras
    _unit(
        "rae-ngle",
        "rae-ngle:manual-2010",
        "que-galicado",
        "Que galicado",
        "grammar_usage",
        ("gramatica", "relativos"),
        aliases=["que galicado", "es por eso que", "fue entonces que"],
        section="relativos / galicismo",
        definition="Criterio para reescribir es por eso que y fue entonces que con relativo o con nexo espanol.",
        statement="La formula es... que calcada del frances se sustituye por por eso, entonces o un relativo con antecedente claro.",
        excerpt="Resumen editorial: el galicismo es inteligible, pero en prosa espanola cuidada suena a calco y diluye el foco.",
        signals=["es por eso que", "fue entonces que", "es ahi que"],
        risks=["cazar un que relativo legitimo"],
        contexts=["estilo", "revision gramatical"],
    ),
    _unit(
        "rae-ngle",
        "rae-ngle:manual-2010",
        "relativo-especificativo-explicativo",
        "Relativo especificativo y explicativo",
        "grammar_concept",
        ("gramatica", "relativos"),
        aliases=["especificativo", "explicativo", "coma del relativo"],
        section="oraciones de relativo",
        definition="Criterio para que la coma del relativo no cambie quien queda dentro o fuera del grupo.",
        statement="Sin coma, el relativo restringe; con coma, anade informacion. Poner o quitar la coma cambia el referente.",
        excerpt="Resumen editorial: la distincion no es adorno tipografico. 'Los alumnos que llegaron tarde' no es el mismo conjunto que 'los alumnos, que llegaron tarde'.",
        signals=[", que", "el cual", "quienes"],
        risks=["unificar todas las relativas con coma"],
        contexts=["puntuacion", "revision gramatical"],
        node_type="norma",
        claim_type="grammatical",
        domain="grammar.syntax",
    ),
    _unit(
        "rae-ngle",
        "rae-ngle:manual-2010",
        "se-impersonal-y-reflejo",
        "Se impersonal y se reflejo",
        "grammar_usage",
        ("gramatica", "se"),
        aliases=["se impersonal", "se reflejo", "pasiva refleja"],
        section="se",
        definition="Criterio para no mezclar el se que oculta agente con el se del verbo pronominal.",
        statement="Si se puede preguntar quien lo hace, el se impersonal o la pasiva refleja piden concordancia coherente; el se pronominal no se 'corrige' anadiendo agente.",
        excerpt="Resumen editorial: la confusion produce frases como se venden pisos frente a se vende pisos, o un se reflejo leido como pasiva.",
        signals=["se venden", "se necesita personas", "se arrepiente"],
        risks=["anadir un sujeto a un verbo pronominal"],
        contexts=["revision gramatical", "avisos"],
    ),
    _unit(
        "rae-ngle",
        "rae-ngle:manual-2010",
        "anacoluto",
        "Anacoluto",
        "grammar_usage",
        ("gramatica", "construccion"),
        aliases=["anacoluto", "quiebro sintactico"],
        section="anacoluto",
        definition="Criterio para detectar un sujeto o un tema que no termina en el verbo que parecia esperarlo.",
        statement="Si la frase arranca con un tema y el verbo concuerda con otra cosa, hay anacoluto; se reordena o se cierra el primer tramo.",
        excerpt="Resumen editorial: el habla lo tolera; la prosa escrita lo siente como tropiezo salvo que imite voz.",
        signals=["en cuanto a", "respecto a", "el problema es cuando"],
        risks=["alisar un quiebro de personaje"],
        contexts=["claridad", "edicion"],
    ),
    # OLE extras
    _unit(
        "rae-ole",
        "rae-ole:edicion-2010",
        "tilde-en-mayusculas",
        "Tilde en mayusculas",
        "orthography_rule",
        ("ortografia", "acentuacion"),
        aliases=["mayusculas", "tilde", "acento grafico"],
        section="tilde en mayusculas",
        definition="Criterio para tildar tambien las mayusculas cuando la palabra lo pide.",
        statement="La mayuscula no anula la tilde. Titulos, siglas lexicalizadas y nombres propios siguen la acentuacion grafica.",
        excerpt="Resumen editorial: la idea de que las mayusculas no se tildan es residual; la norma vigente tilda.",
        signals=["ANGEL", "PERIODICO", "titulo en versales"],
        risks=["tildar siglas no lexicalizadas"],
        contexts=["ortografia", "titulares"],
        claim_type="orthographic",
        domain="orthography.accent",
    ),
    _unit(
        "rae-ole",
        "rae-ole:edicion-2010",
        "interrogacion-de-apertura",
        "Signos de interrogacion de apertura",
        "orthography_rule",
        ("ortografia", "puntuacion"),
        aliases=["¿", "interrogacion", "exclamacion"],
        section="signos de interrogacion",
        definition="Criterio para abrir la pregunta o la exclamacion donde empieza, no solo al final.",
        statement="En espanol la pregunta se marca al inicio del tramo interrogativo; el signo final no basta.",
        excerpt="Resumen editorial: el cierre ingles se ha colado en mensajes; en texto editable se restaura la apertura.",
        signals=["que te parece?", "como estas?"],
        risks=["poner ¿ delante de un complemento que no pregunta"],
        contexts=["correccion", "mensajes"],
        claim_type="orthographic",
        domain="orthography.punctuation",
    ),
    _unit(
        "rae-ole",
        "rae-ole:edicion-2010",
        "dialogo-con-raya",
        "Dialogo con raya",
        "orthography_rule",
        ("ortografia", "dialogo"),
        aliases=["raya", "dialogo", "guion largo"],
        section="raya de dialogo",
        definition="Criterio para interpolar parlamentos con raya, no con guion corto ni con menos.",
        statement="El parlamento se abre con raya; las acotaciones se cierran con raya si el habla sigue. El guion corto no hace ese trabajo.",
        excerpt="Resumen editorial: mezclar comillas inglesas, guion y raya en el mismo dialogo cansa al lector.",
        signals=["- hola", "--dijo", "—dijo—"],
        risks=["unificar un texto que ya usa comillas de forma coherente"],
        contexts=["narrativa", "edicion"],
        claim_type="orthographic",
        domain="orthography.dialogue",
    ),
    _unit(
        "rae-ole",
        "rae-ole:edicion-2010",
        "coma-vocativo",
        "Coma de vocativo",
        "orthography_rule",
        ("ortografia", "coma"),
        aliases=["vocativo", "coma", "hola ana"],
        section="coma del vocativo",
        definition="Criterio para aislar el vocativo con coma y no pegarlo al verbo.",
        statement="El nombre al que se habla no es sujeto silencioso: va entre comas o al borde de la frase.",
        excerpt="Resumen editorial: 'vamos ninos' y 'vamos, ninos' no piden lo mismo. La coma evita leer el nombre como complemento.",
        signals=["hola ana", "gracias maria", "oiga senor"],
        risks=["poner coma en un sujeto antepuesto"],
        contexts=["correccion", "cartas"],
        claim_type="orthographic",
        domain="orthography.punctuation",
    ),
    # Fundéu
    _unit(
        "fundeu-recomendaciones",
        "fundeu-recomendaciones:web-2026",
        "solo-sin-tilde",
        "Solo sin tilde",
        "orthography_rule",
        ("ortografia", "tilde diacritica"),
        aliases=["solo", "sólo", "tilde diacritica"],
        section="solo",
        definition="Criterio vigente: solo adverbio no lleva tilde; la diacritica se reserva a casos de ambiguedad real y rara.",
        statement="En la norma actual, solo se escribe sin tilde. No se restaura el acento 'para que se lea adverbio'.",
        excerpt="Resumen editorial: Fundeu y la RAE coinciden en simplificar. La tilde de solo queda como excepcion, no como costumbre.",
        signals=["sólo", "aun", "este"],
        risks=["dejar un solo ambiguo en un titulo juridico sin resolverlo con orden"],
        contexts=["ortografia", "edicion"],
        claim_type="orthographic",
        domain="orthography.accent",
    ),
    _unit(
        "fundeu-recomendaciones",
        "fundeu-recomendaciones:web-2026",
        "cifras-o-letras",
        "Cifras o letras",
        "editorial_style_tool",
        ("estilo", "numeracion"),
        aliases=["numeros", "cifras", "letras"],
        section="numeracion",
        definition="Criterio para escribir cantidades con letras o cifras segun el tipo de texto, no segun el capricho de cada parrafo.",
        statement="Un mismo texto no mezcla 3 y tres para la misma clase de dato. Las cantidades redondas de relato van en letras; las tecnicas, en cifras.",
        excerpt="Resumen editorial: la recomendacion busca consistencia. Un acta no se escribe como un cuento, ni al reves.",
        signals=["3 dias", "tres %", "2.000"],
        risks=["pasar a letras un codigo, un ano o un porcentaje"],
        contexts=["estilo editorial", "informes"],
        node_type="metodo",
        claim_type="stylistic",
        domain="style.numbers",
    ),
    _unit(
        "fundeu-recomendaciones",
        "fundeu-recomendaciones:web-2026",
        "cargos-en-minuscula",
        "Cargos en minuscula",
        "editorial_style_tool",
        ("ortografia", "mayusculas"),
        aliases=["presidente", "directora", "cargo"],
        section="mayusculas de cargo",
        definition="Criterio para escribir los cargos en minuscula cuando acompanjan al nombre o van genericos.",
        statement="El cargo no se pone en mayuscula por respeto. La mayuscula se reserva a institucion o uso protocolario muy tasado.",
        excerpt="Resumen editorial: la mayuscula de cargo hincha el texto administrativo. La minuscula no quita autoridad.",
        signals=["el Presidente", "la Directora General"],
        risks=["minusculizar una sigla o un nombre propio"],
        contexts=["noticias", "actas", "edicion"],
        node_type="norma",
        claim_type="orthographic",
        domain="orthography.caps",
    ),
    _unit(
        "fundeu-recomendaciones",
        "fundeu-recomendaciones:web-2026",
        "comillas-latinas",
        "Comillas latinas",
        "orthotypography_rule",
        ("ortografia", "comillas"),
        aliases=["comillas", "«»", "latinas"],
        section="comillas",
        definition="Criterio para preferir comillas angulares en espanol y anidar con dobles y simples.",
        statement="La jerarquia « ” ‘ » evita mezclar el ingles y el espanol en el mismo parrafo.",
        excerpt="Resumen editorial: las comillas rectas de teclado valen en borrador; en texto listo se normalizan.",
        signals=['"cita"', "«cita»"],
        risks=["cambiar comillas en codigo o en un original que las usa como grafica"],
        contexts=["edicion", "ortotipografia"],
        claim_type="orthographic",
        domain="orthography.quotes",
    ),
    _unit(
        "fundeu-recomendaciones",
        "fundeu-recomendaciones:web-2026",
        "decadas-en-cifras",
        "Decadas en cifras",
        "editorial_style_tool",
        ("estilo", "fechas"),
        aliases=["anos 90", "decada", "1990"],
        section="decadas",
        definition="Criterio para escribir decadas sin apostrofo ingles y con articulo claro.",
        statement="Se evita los 90's. En espanol: los anos noventa o la decada de 1990.",
        excerpt="Resumen editorial: el apostrofo de decade inglesa no aporta nada y choca con la ortografia espanola.",
        signals=["los 90's", "los 90s", "los noventa"],
        risks=["reescribir una cita que imita ingles a proposito"],
        contexts=["cronica", "edicion"],
        node_type="norma",
        claim_type="stylistic",
        domain="style.dates",
    ),
    _unit(
        "fundeu-recomendaciones",
        "fundeu-recomendaciones:web-2026",
        "al-contraccion",
        "Contraccion al y del",
        "orthography_rule",
        ("ortografia", "contraccion"),
        aliases=["al", "del", "a el"],
        section="contracciones",
        definition="Criterio para contraer a + el y de + el salvo que el sea parte de un nombre propio que no se toca.",
        statement="A el y de el se contraen en al y del. No se contrae si el articulo forma parte de un nombre fijo.",
        excerpt="Resumen editorial: la excepcion vive en periodicos y obras ('El Pais', 'El Quijote' en algunos usos). Fuera de ahi, se contrae.",
        signals=["a el director", "de el informe"],
        risks=["contrer un El de cabecera"],
        contexts=["correccion"],
        claim_type="orthographic",
        domain="orthography.contraction",
    ),
    # Moliner
    _unit(
        "moliner-due",
        "moliner-due:edicion-referencia",
        "intencion-de-la-palabra",
        "Intencion de la palabra",
        "lexical_choice_tool",
        ("lexico", "uso"),
        aliases=["intencion", "empleo", "moliner"],
        section="uso",
        definition="Criterio para preguntar que quiere hacer la palabra en la frase, no que figura en un sinonimo facil.",
        statement="Una palabra de oficio se elige por la intencion (precisar, suavizar, cargar). Si no hace ese trabajo, se cambia.",
        excerpt="Resumen editorial: el diccionario de uso ensena a mirar el empleo. La ficha traduce eso a una pregunta de taller: que hace aqui esta palabra.",
        signals=["sinonimo por sinonimo", "palabra hueca", "matiz perdido"],
        risks=["buscar rareza para parecer preciso"],
        contexts=["lexico", "taller"],
        node_type="metodo",
        claim_type="lexical",
        domain="lexicon.usage",
    ),
    _unit(
        "moliner-due",
        "moliner-due:edicion-referencia",
        "uso-vivo",
        "Uso vivo",
        "lexical_choice_tool",
        ("lexico", "uso"),
        aliases=["uso vivo", "palabra viva", "desuso"],
        section="uso vivo",
        definition="Criterio para preferir la palabra que el lector reconoce en su empleo actual, no la reliquia de articulo.",
        statement="Si el sentido vive en el habla culta actual, se sostiene; si solo vive en el diccionario, se busca el empleo de hoy.",
        excerpt="Resumen editorial: Moliner ordena el idioma como se usa. La edicion no resucita voces para dar barniz.",
        signals=["vocablo", "deceso", "prohombre"],
        risks=["aplanar un arcaismo de personaje"],
        contexts=["lexico", "prosa general"],
        node_type="metodo",
        claim_type="lexical",
        domain="lexicon.usage",
    ),
    _unit(
        "moliner-due",
        "moliner-due:edicion-referencia",
        "matiz-afectivo",
        "Matiz afectivo",
        "lexical_choice_tool",
        ("lexico", "matiz"),
        aliases=["afectivo", "carga", "connotacion"],
        section="matiz",
        definition="Criterio para no cambiar una palabra por otra de denotacion parecida y carga distinta.",
        statement="Flaco, delgado y escuálido no hacen el mismo trabajo. El matiz afectivo es parte del significado.",
        excerpt="Resumen editorial: el diccionario de uso senala vecindades. La edicion elige vecino, no sinonimo plano.",
        signals=["delgado", "flaco", "enjuto", "tonto", "ingenuo"],
        risks=["neutralizar una carga que el autor quiere"],
        contexts=["lexico", "tono"],
        node_type="metodo",
        claim_type="lexical",
        domain="lexicon.nuance",
    ),
    _unit(
        "moliner-due",
        "moliner-due:edicion-referencia",
        "ejemplo-como-prueba",
        "Ejemplo como prueba de uso",
        "lexical_choice_tool",
        ("lexico", "metodo"),
        aliases=["ejemplo", "empleo", "colocacion"],
        section="ejemplos",
        definition="Criterio para comprobar una palabra en una frase posible, no aislada.",
        statement="Si no se puede inventar un ejemplo natural con esa palabra, no entra en el texto.",
        excerpt="Resumen editorial: Moliner ensena con empleos. La ficha pide la misma prueba en el borrador.",
        signals=["palabra aislada", "no suena", "calco"],
        risks=["rechazar un termino tecnico porque el ejemplo cotidiano falla"],
        contexts=["lexico", "taller"],
        node_type="metodo",
        claim_type="lexical",
        domain="lexicon.usage",
    ),
    _unit(
        "moliner-due",
        "moliner-due:edicion-referencia",
        "familia-de-palabras-due",
        "Familia de palabras como red de uso",
        "lexical_choice_tool",
        ("lexico", "familia"),
        aliases=["familia lexica", "derivados"],
        section="familia de palabras",
        definition="Criterio para recorrer derivados antes de saltar a un sinonimo lejano.",
        statement="A veces el matiz esta en el derivado (claridad, aclarar, claro), no en un sinonimo de otro campo.",
        excerpt="Resumen editorial: la red de familia evita el salto a un extranjerismo o a un culto innecesario.",
        signals=["claridad", "elucidacion", "explicitez"],
        risks=["derivar en cadena hasta un neologismo feo"],
        contexts=["lexico"],
        node_type="metodo",
        claim_type="lexical",
        domain="lexicon.family",
    ),
    _unit(
        "moliner-due",
        "moliner-due:edicion-referencia",
        "palabra-de-oficio",
        "Palabra de oficio",
        "lexical_choice_tool",
        ("lexico", "oficio"),
        aliases=["oficio", "palabra justa", "herramienta"],
        section="precision",
        definition="Criterio para buscar la palabra que hace el trabajo del oficio (cortar, sostener, medir), no la que adorna.",
        statement="En un texto que opera, cada nombre y cada verbo deben servir. El adorno se va a otro genero.",
        excerpt="Resumen editorial: el diccionario de uso premia el empleo. La ficha aplica eso a avisos, informes y prosa util.",
        signals=["realizar", "llevar a cabo", "elemento", "tema"],
        risks=["quitar color a un texto literario"],
        contexts=["prosa util", "informes"],
        node_type="metodo",
        claim_type="lexical",
        domain="lexicon.usage",
    ),
    # Seco
    _unit(
        "seco-dudas",
        "seco-dudas:edicion-referencia",
        "regimen-preposicional",
        "Regimen preposicional",
        "grammar_usage",
        ("gramatica", "regimen"),
        aliases=["regimen", "preposicion", "seco"],
        section="regimen",
        definition="Criterio para fijar la preposicion que el verbo o el adjetivo rigen, no la que 'suena cerca'.",
        statement="Influir en, coincidir con, aficion a: el regimen no se improvisa. Si hay duda, se consulta antes de publicar.",
        excerpt="Resumen editorial: Seco organiza la dificultad por construccion. La ficha pide no resolver el regimen por analogia facil.",
        signals=["influir a", "coincidir en con", "aficion por"],
        risks=["imponer un regimen culto contra un uso ya general y aceptado"],
        contexts=["revision gramatical", "edicion"],
    ),
    _unit(
        "seco-dudas",
        "seco-dudas:edicion-referencia",
        "construccion-fija",
        "Construccion fija",
        "grammar_usage",
        ("gramatica", "construcciones"),
        aliases=["construccion", "esquema", "duda"],
        section="construcciones",
        definition="Criterio para no desmontar un esquema fijo (en relacion con, a tenor de) sustituyendo piezas.",
        statement="Las construcciones de duda se tratan como unidades. Si se quiere otra, se cambia el bloque entero.",
        excerpt="Resumen editorial: Seco lista dificultades de ensamblaje. La edicion no hace bricolaje dentro del esquema.",
        signals=["en base a", "de acuerdo a", "a nivel de"],
        risks=["cazar locuciones ya asentadas en el ambito del texto"],
        contexts=["edicion", "prosa administrativa"],
    ),
    _unit(
        "seco-dudas",
        "seco-dudas:edicion-referencia",
        "uso-culto-y-comun",
        "Uso culto y uso comun",
        "grammar_usage",
        ("gramatica", "registro"),
        aliases=["culto", "comun", "norma"],
        section="uso culto y comun",
        definition="Criterio para no imponer el uso de escuela cuando el comun es el del texto, ni al reves.",
        statement="Hay dudas donde conviven un uso culto y uno comun. La edicion elige el del lector y se mantiene.",
        excerpt="Resumen editorial: Seco distingue niveles. Un aviso vecinal no se escribe como una memoria academica.",
        signals=["vosotros", "ustedes", "leismo culto"],
        risks=["corregir la voz de un personaje al uso de academia"],
        contexts=["registro", "edicion"],
        node_type="metodo",
    ),
    _unit(
        "seco-dudas",
        "seco-dudas:edicion-referencia",
        "concordancia-ad-sensum",
        "Concordancia ad sensum",
        "grammar_usage",
        ("gramatica", "concordancia"),
        aliases=["ad sensum", "colectivo", "la mayoria"],
        section="concordancia",
        definition="Criterio para decidir si un colectivo concuerda en singular gramatical o en plural de sentido.",
        statement="La mayoria, un grupo, un 20 %: el verbo puede ir al colectivo o a las personas. En un texto, se elige un criterio y no se mezcla.",
        excerpt="Resumen editorial: Seco senala la vacilacion. La edicion evita 'la mayoria quiere... y salen'.",
        signals=["la mayoria quieren", "un grupo de vecinos pide"],
        risks=["forzar singular en un colectivo que ya se leyo como personas"],
        contexts=["revision gramatical", "noticias"],
    ),
    _unit(
        "seco-dudas",
        "seco-dudas:edicion-referencia",
        "deque-regimen-seco",
        "Regimen de que y de que",
        "grammar_usage",
        ("gramatica", "regimen"),
        aliases=["de que", "regimen de que"],
        section="de que",
        definition="Criterio complementario del dequeismo: no todas las secuencias de que son error.",
        statement="Algunos verbos y nombres rigen de que. Quitar de por sistema crea queismo.",
        excerpt="Resumen editorial: Seco y el DPD se miran. La ficha recuerda comprobar el regimen, no aplicar una regla unica.",
        signals=["me alegro que", "la idea de que", "convencido que"],
        risks=["anadir de a verbos que no lo rigen"],
        contexts=["revision gramatical"],
    ),
    _unit(
        "seco-dudas",
        "seco-dudas:edicion-referencia",
        "verbo-con-preposicion",
        "Verbo con preposicion",
        "grammar_usage",
        ("gramatica", "regimen"),
        aliases=["depender de", "consistir en", "aspirar a"],
        section="verbos con preposicion",
        definition="Criterio para no dejar un verbo de regimen sin su preposicion o con otra prestada.",
        statement="Depender, consistir, aspirar, coincidir: cada uno trae preposicion. La analogia con el ingles o con un sinonimo no vale.",
        excerpt="Resumen editorial: las listas de regimen existen porque el oido falla entre lenguas y entre sinonimos.",
        signals=["depende a", "consiste de", "aspira en"],
        risks=["calcar un regimen de traduccion"],
        contexts=["revision gramatical", "traduccion"],
    ),
    # Oficio en español (Cassany / Reyes)
    _unit(
        "cassany-cocina-escritura",
        "cassany-cocina-escritura:edicion-referencia",
        "prosa-hablada-y-escrita",
        "Prosa hablada y prosa escrita",
        "writing_method",
        ("estilo", "oficio"),
        aliases=["oralidad", "escrito", "transcripcion"],
        section="hablar y escribir",
        definition="Criterio para no pegar el habla al papel ni al reves: cada canal tiene su sintaxis.",
        statement="Lo que se dice en voz alta con gestos no se copia en un parrafo. Lo escrito demasiado oral se reordena; lo escrito demasiado rígido se destensa.",
        excerpt="Resumen editorial: Cassany separa las cocinas. La ficha pide oir el texto y luego decidir si el canal es el correcto.",
        signals=["o sea", "entonces pues", "como te decia"],
        risks=["matar la voz de un relato oral"],
        contexts=["taller", "prosa util"],
        node_type="metodo",
        claim_type="stylistic",
        domain="writing.craft",
    ),
    _unit(
        "cassany-cocina-escritura",
        "cassany-cocina-escritura:edicion-referencia",
        "mostrar-antes-de-explicar",
        "Mostrar antes de explicar",
        "writing_method",
        ("estilo", "oficio"),
        aliases=["mostrar", "explicar", "ejemplo primero"],
        section="mostrar y decir",
        definition="Criterio para poner el caso o el dato antes del comentario, cuando el lector aun no ha visto nada.",
        statement="Si el parrafo predica sin ensenar, se invierte: primero el hecho, despues la valoracion.",
        excerpt="Resumen editorial: el taller de escritura espanola insiste en no empezar por la moraleja. La ficha lo aplica a informe y a escena.",
        signals=["es importante senalar", "cabe destacar", "sin duda"],
        risks=["quitar una tesis que el genero exige al inicio"],
        contexts=["taller", "ensayo"],
        node_type="metodo",
        claim_type="stylistic",
        domain="writing.craft",
    ),
    _unit(
        "cassany-cocina-escritura",
        "cassany-cocina-escritura:edicion-referencia",
        "adjetivo-innecesario",
        "Adjetivo innecesario",
        "writing_method",
        ("estilo", "adjetivo"),
        aliases=["adjetivo", "epiteto", "calificativo"],
        section="adjetivos",
        definition="Criterio para borrar el calificativo que no anade medida, contraste ni percepcion.",
        statement="Un adjetivo que el sustantivo ya contiene (futuro venidero, breve resumen) se corta.",
        excerpt="Resumen editorial: la cocina de la escritura recela del adjetivo automatico. Se deja el que cambia el objeto.",
        signals=["importante", "relevante", "claro y conciso"],
        risks=["quitar un adjetivo de caracter o de campo semantico"],
        contexts=["estilo", "edicion"],
        node_type="metodo",
        claim_type="stylistic",
        domain="writing.craft",
    ),
    _unit(
        "reyes-arte-escribir",
        "reyes-arte-escribir:edicion-2012",
        "hipotaxis-controlada",
        "Hipotaxis controlada",
        "writing_method",
        ("estilo", "sintaxis"),
        aliases=["hipotaxis", "subordinacion", "frase larga"],
        section="subordinacion",
        definition="Criterio para que la frase larga espanola lleve un verbo principal visible y subordinadas con trabajo.",
        statement="La hipotaxis no es un defecto: lo es la subordinada que no informa. Se poda la rama, no el arbol entero.",
        excerpt="Resumen editorial: el espanol escrito tolera mas subordinacion que el ingles de manual. La ficha pide control, no frases de telegrama.",
        signals=["que que que", "el cual el cual", "frase de diez lineas"],
        risks=["cortar una frase periodica que ya respira"],
        contexts=["estilo", "ensayo"],
        node_type="metodo",
        claim_type="stylistic",
        domain="writing.craft",
    ),
    _unit(
        "reyes-arte-escribir",
        "reyes-arte-escribir:edicion-2012",
        "parataxis-y-ritmo",
        "Parataxis y ritmo",
        "writing_method",
        ("estilo", "ritmo"),
        aliases=["parataxis", "yuxtaposicion", "ritmo"],
        section="parataxis",
        definition="Criterio para usar frases cortas seguidas cuando el texto necesita golpe, no cuando se ha perdido el hilo.",
        statement="La parataxis da ritmo. Encadenada sin plan parece nerviosismo. Se alterna con una subordinada que cierre el pensamiento.",
        excerpt="Resumen editorial: el arte de escribir bien en espanol trabaja el oido. La ficha pide oir el golpe y el descanso.",
        signals=["frase. Frase. Frase.", "y y y"],
        risks=["unir con que todo lo que pedia un punto"],
        contexts=["estilo", "narrativa"],
        node_type="metodo",
        claim_type="stylistic",
        domain="writing.craft",
    ),
    _unit(
        "reyes-arte-escribir",
        "reyes-arte-escribir:edicion-2012",
        "que-encadenado",
        "Que encadenado",
        "writing_method",
        ("estilo", "relativos"),
        aliases=["que que", "relativo en cadena"],
        section="relativos encadenados",
        definition="Criterio para no colgar tres que seguidos que obligan a releer.",
        statement="Si hay mas de un que relativo o completivo en la misma frase, se nombra, se corta o se pasa a gerundio de manera o a dos oraciones.",
        excerpt="Resumen editorial: el espanol abusa del que porque es barato. La edicion lo encarece.",
        signals=["que que", "el hecho de que", "dicho que"],
        risks=["quitar un que necesario y dejar anacoluto"],
        contexts=["claridad", "edicion"],
        node_type="metodo",
        claim_type="stylistic",
        domain="writing.craft",
    ),
    _unit(
        "reyes-arte-escribir",
        "reyes-arte-escribir:edicion-2012",
        "estilo-indirecto-libre",
        "Estilo indirecto libre",
        "writing_method",
        ("narrativa", "voz"),
        aliases=["indirecto libre", "voz", "pensamiento"],
        section="estilo indirecto libre",
        definition="Criterio para marcar si el pensamiento es del narrador o del personaje, sin comillas ni dijo.",
        statement="El indirecto libre mezcla voces. Si el lector no sabe quien valora, se ancla con un verbo de percepcion o se pasa a dialogo.",
        excerpt="Resumen editorial: es una herramienta de la prosa espanola moderna. La ficha pide control de la frontera, no prohibicion.",
        signals=["pensaria", "claro que", "como iba a"],
        risks=["explicitar siempre y matar el efecto"],
        contexts=["narrativa"],
        node_type="metodo",
        claim_type="literary",
        domain="writing.craft",
    ),
    _unit(
        "cassany-cocina-escritura",
        "cassany-cocina-escritura:edicion-referencia",
        "corte-de-frase-espanola",
        "Corte de frase espanola",
        "writing_method",
        ("estilo", "frase"),
        aliases=["corte", "punto", "aliento"],
        section="frase",
        definition="Criterio para cortar donde el aliento y la informacion coinciden, no cada doce palabras por norma importada.",
        statement="El espanol escrito admite frase amplia si el verbo principal se ve. Se corta cuando el lector pierde el sujeto o la novedad.",
        excerpt="Resumen editorial: no se aplica el recetario de frase corta inglesa. Se aplica el oido del parrafo espanol.",
        signals=["punto corto en serie", "frase de pagina"],
        risks=["imitar telegrama"],
        contexts=["estilo", "taller"],
        node_type="metodo",
        claim_type="stylistic",
        domain="writing.craft",
    ),
    _unit(
        "cassany-cocina-escritura",
        "cassany-cocina-escritura:edicion-referencia",
        "gerundio-narrativo-riesgo",
        "Gerundio narrativo de riesgo",
        "writing_method",
        ("estilo", "gerundio"),
        aliases=["gerundio narrativo", "relato"],
        section="gerundio en relato",
        definition="Criterio de oficio: el gerundio de escena pinta manera; el de trama empuja el tiempo y suele fallar.",
        statement="En relato, se deja el gerundio que describe el modo de una accion simultanea. El que avanza capitulo se cambia a verbo finito.",
        excerpt="Resumen editorial: coincide con la duda gramatical del DPD, aplicada al taller de escena.",
        signals=["entrando, vio", "cayendo, murio"],
        risks=["prohibir gerundios de manera"],
        contexts=["narrativa", "taller"],
        node_type="metodo",
        claim_type="stylistic",
        domain="writing.craft",
    ),
]


def _records_for_unit(unit: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    slug = unit["slug"]
    source_id = unit["source_id"]
    node_id = f"{source_id}-{slug}"
    card_id = f"card-{slug}"
    evidence_id = f"ev-{source_id}-{slug}"
    claim_id = f"claim-{source_id}-{slug}"
    edition_id = unit["edition_id"]
    primary, secondary = unit["branch"]
    segment_id = f"{edition_id}:{slug}:seg-1"
    return {
        "knowledge_nodes": [
            {
                "id": node_id,
                "source_id": source_id,
                "node_type": unit["node_type"],
                "title": unit["name"],
                "canonical_name": unit["name"],
                "aliases": unit["aliases"],
                "primary_branch": primary,
                "secondary_branch": secondary,
                "summary": unit["definition"],
                "short_definition": unit["definition"],
                "long_definition": (
                    f"Concepto validado desde un resumen editorial de {edition_id} "
                    f"y publicado como parte del lote knowledge-v52."
                ),
                "status": "published",
                "version": VERSION,
                "created_at": CREATED_AT,
                "published_at": PUBLISHED_AT,
            }
        ],
        "knowledge_cards": [
            {
                "id": card_id,
                "card_type": unit["card_type"],
                "name": unit["name"],
                "definition": unit["definition"],
                "confidence": 0.72,
                "version": VERSION,
                "payload": {
                    "contexts": unit["contexts"],
                    "risks": unit["risks"],
                    "signals": unit["signals"],
                },
            }
        ],
        "knowledge_evidence_items": [
            {
                "id": evidence_id,
                "source_id": source_id,
                "source_edition_id": edition_id,
                "node_id": node_id,
                "evidence_type": "editorial_summary",
                "reference": f"edicion de referencia > {unit['section']} > resumen editorial 1",
                "locator": {
                    "edition": "edicion de referencia",
                    "section": unit["section"],
                    "segment_id": segment_id,
                },
                "excerpt": unit["excerpt"],
                "context": "seed_spanish_writing_v52_batch",
                "confidence": 0.72,
                "confidence_level": 3,
                "status": "published",
                "revision": 1,
                "incorporated_by": AUTHOR,
                "reviewed_by": AUTHOR,
                "version": VERSION,
                "created_at": CREATED_AT,
                "updated_at": PUBLISHED_AT,
            }
        ],
        "knowledge_claims": [
            {
                "id": claim_id,
                "card_id": card_id,
                "node_id": node_id,
                "evidence_id": evidence_id,
                "claim_type": unit["claim_type"],
                "statement": unit["statement"],
                "domain": unit["domain"],
                "scope": {
                    "geography": "panhispanic",
                    "language": "es",
                    "period": "contemporary",
                    "register": "general",
                    "text_type": "writing",
                },
                "status": "published",
                "origin": "approved_knowledge_proposal",
                "revision": 1,
                "related_node_ids": [],
                "confidence": 0.72,
                "version": VERSION,
                "created_at": CREATED_AT,
                "published_at": PUBLISHED_AT,
                "updated_at": PUBLISHED_AT,
            }
        ],
        "knowledge_claim_evidence_links": [
            {
                "id": f"{claim_id}:{evidence_id}:primary",
                "claim_id": claim_id,
                "evidence_id": evidence_id,
                "role": "primary",
                "created_at": CREATED_AT,
            }
        ],
        "knowledge_claim_revisions": [
            {
                "id": f"{claim_id}:r1",
                "claim_id": claim_id,
                "revision": 1,
                "author": AUTHOR,
                "reason": "registro inicial del lote knowledge-v52",
                "changed_fields": ["statement", "claim_type", "node_id", "domain", "scope", "status"],
                "previous_claim": {},
                "new_claim": {
                    "claim_type": unit["claim_type"],
                    "domain": unit["domain"],
                    "evidence_id": evidence_id,
                    "node_id": node_id,
                    "scope": {
                        "geography": "panhispanic",
                        "language": "es",
                        "period": "contemporary",
                        "register": "general",
                        "text_type": "writing",
                    },
                    "statement": unit["statement"],
                    "status": "published",
                },
                "knowledge_version": VERSION,
                "created_at": CREATED_AT,
            }
        ],
        "knowledge_evidence_revisions": [
            {
                "id": f"{evidence_id}:r1",
                "evidence_id": evidence_id,
                "revision": 1,
                "author": AUTHOR,
                "reason": "registro inicial del lote knowledge-v52",
                "changes": {
                    "locator": {
                        "edition": "edicion de referencia",
                        "section": unit["section"],
                        "segment_id": segment_id,
                    },
                    "source_edition_id": edition_id,
                    "status": "published",
                },
                "created_at": CREATED_AT,
            }
        ],
        "knowledge_object_revisions": [
            {
                "id": f"rev-knowledge_card-{card_id}-r1",
                "object_type": "knowledge_card",
                "object_id": card_id,
                "revision_number": 1,
                "object_version": f"{card_id}@r1",
                "knowledge_version": VERSION,
                "status": "active",
                "change_type": "created",
                "author": AUTHOR,
                "reason": "registro inicial segun contrato de versionado V1",
                "before": {},
                "after": {
                    "card_type": unit["card_type"],
                    "name": unit["name"],
                    "payload_keys": ["contexts", "risks", "signals"],
                    "version": VERSION,
                },
                "previous_revision": None,
                "replaces_object_id": None,
                "replaced_by_object_id": None,
                "created_at": CREATED_AT,
                "updated_at": CREATED_AT,
            }
        ],
        "knowledge_relations": [
            {
                "id": f"rel-claim-{claim_id}-aplicacion_de-knowledge_card-{card_id}",
                "relation_type": "aplicacion_de",
                "source_entity_type": "claim",
                "source_entity_id": claim_id,
                "target_entity_type": "knowledge_card",
                "target_entity_id": card_id,
                "direction": "outgoing",
                "cardinality": "N:1",
                "weight": 1.0,
                "confidence": 0.72,
                "context": unit["domain"],
                "status": "published",
                "version": VERSION,
                "created_at": CREATED_AT,
                "updated_at": PUBLISHED_AT,
            },
            {
                "id": f"rel-claim-{claim_id}-sostenido_por-evidence-{evidence_id}",
                "relation_type": "sostenido_por",
                "source_entity_type": "claim",
                "source_entity_id": claim_id,
                "target_entity_type": "evidence",
                "target_entity_id": evidence_id,
                "direction": "outgoing",
                "cardinality": "N:1",
                "weight": 1.0,
                "confidence": 0.72,
                "context": unit["domain"],
                "status": "published",
                "version": VERSION,
                "created_at": CREATED_AT,
                "updated_at": PUBLISHED_AT,
            },
        ],
        "knowledge_node_relations": [
            {
                "id": f"rel-{node_id}-parte_de-lote-v52",
                "relation_type": "relacionado_con",
                "source_node_id": node_id,
                "target_node_id": node_id,
                "direction": "outgoing",
                "cardinality": "N:N",
                "weight": 0.5,
                "confidence": 0.72,
                "context": "spanish_writing_v52_batch",
                "status": "published",
                "version": VERSION,
                "created_at": CREATED_AT,
                "updated_at": PUBLISHED_AT,
            }
        ],
    }


def _ingestion_batch(source_id: str, edition_id: str, *, blocked: bool) -> dict[str, Any]:
    return {
        "id": f"ingest-{edition_id}",
        "source_id": source_id,
        "source_edition_id": edition_id,
        "batch_label": "lote inicial pendiente de adquisicion",
        "scope": "edicion completa pendiente de identificacion documental",
        "status": "blocked" if blocked else "registered",
        "author": AUTHOR,
        "tools": ["manual_review"],
        "model_used": None,
        "configuration": {
            "ai_origin_required": "automated",
            "publishes_directly": False,
            "unit": "one_source_one_edition_one_batch",
        },
        "progress": {
            "candidate_version": False,
            "document_structure": False,
            "edition": not blocked,
            "extraction": False,
            "normalization": False,
            "registered_source": True,
            "review": False,
            "segmentation": False,
            "validation": False,
        },
        "metrics": {
            "cards": 0,
            "claims": 0,
            "contradictions": 0,
            "coverage": 0,
            "duplicates": 0,
            "elapsed_seconds": 0,
            "evidence": 0,
            "nodes_created": 0,
            "relations": 0,
        },
        "decisions": [],
        "blockers": (
            ["missing_edition", "missing_location", "document_structure_pending"] if blocked else []
        ),
        "result": "not_started",
        "created_at": CREATED_AT,
        "updated_at": CREATED_AT,
    }


def _object_revision(object_type: str, object_id: str, after: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": f"rev-{object_type}-{object_id}-r1",
        "object_type": object_type,
        "object_id": object_id,
        "revision_number": 1,
        "object_version": f"{object_id}@r1",
        "knowledge_version": VERSION,
        "status": "active",
        "change_type": "created",
        "author": AUTHOR,
        "reason": "registro inicial segun contrato de versionado V1",
        "before": {},
        "after": after,
        "previous_revision": None,
        "replaces_object_id": None,
        "replaced_by_object_id": None,
        "created_at": CREATED_AT,
        "updated_at": CREATED_AT,
    }


def v52_new_tables() -> dict[str, list[dict[str, Any]]]:
    tables: dict[str, list[dict[str, Any]]] = {
        "knowledge_versions": [{"id": VERSION, "status": "published", "published_at": PUBLISHED_AT}],
        "knowledge_sources": deepcopy(NEW_SOURCES),
        "knowledge_source_editions": deepcopy(NEW_EDITIONS),
        "knowledge_ingestion_batches": [
            _ingestion_batch("moliner-due", "moliner-due:edicion-referencia", blocked=False),
            _ingestion_batch("moliner-due", "moliner-due:pending-edition", blocked=True),
            _ingestion_batch("seco-dudas", "seco-dudas:edicion-referencia", blocked=False),
            _ingestion_batch("seco-dudas", "seco-dudas:pending-edition", blocked=True),
        ],
        "knowledge_nodes": [],
        "knowledge_cards": [],
        "knowledge_evidence_items": [],
        "knowledge_claims": [],
        "knowledge_claim_evidence_links": [],
        "knowledge_claim_revisions": [],
        "knowledge_evidence_revisions": [],
        "knowledge_object_revisions": [
            _object_revision(
                "source",
                "moliner-due",
                {
                    "authority_level": 5,
                    "catalog_id": "F027",
                    "name": "Diccionario de uso del espanol",
                    "status": "registered",
                },
            ),
            _object_revision(
                "source",
                "seco-dudas",
                {
                    "authority_level": 5,
                    "catalog_id": "F028",
                    "name": "Diccionario de dudas y dificultades de la lengua espanola",
                    "status": "registered",
                },
            ),
            _object_revision(
                "source_edition",
                "moliner-due:edicion-referencia",
                {
                    "acquisition_status": "available",
                    "label": "edicion de referencia",
                    "source_id": "moliner-due",
                    "validation_status": "validated",
                },
            ),
            _object_revision(
                "source_edition",
                "seco-dudas:edicion-referencia",
                {
                    "acquisition_status": "available",
                    "label": "edicion de referencia",
                    "source_id": "seco-dudas",
                    "validation_status": "validated",
                },
            ),
            _object_revision(
                "source_edition",
                "moliner-due:pending-edition",
                {
                    "acquisition_status": "available",
                    "label": "pendiente de identificacion",
                    "source_id": "moliner-due",
                    "validation_status": "validated",
                },
            ),
            _object_revision(
                "source_edition",
                "seco-dudas:pending-edition",
                {
                    "acquisition_status": "available",
                    "label": "pendiente de identificacion",
                    "source_id": "seco-dudas",
                    "validation_status": "validated",
                },
            ),
        ],
        "knowledge_relations": [],
        "knowledge_node_relations": [],
        "knowledge_version_snapshots": [],
    }
    for unit in UNITS:
        bundle = _records_for_unit(unit)
        for table_name, rows in bundle.items():
            tables[table_name].extend(rows)
    return tables


def _row_sort_key(row: dict[str, Any]) -> str:
    if "id" in row:
        return str(row["id"])
    if "version_id" in row:
        return str(row["version_id"])
    return ""


def build_v52_snapshot() -> dict[str, Any]:
    base = load_knowledge_seed_snapshot(BASE_VERSION)
    v51_snap = next(
        item for item in base["tables"]["knowledge_version_snapshots"] if item["version_id"] == BASE_VERSION
    )
    tables: dict[str, list[dict[str, Any]]] = {
        name: deepcopy(rows) for name, rows in base["tables"].items()
    }
    new_tables = v52_new_tables()
    new_ids = {
        "source_ids": [source["id"] for source in new_tables["knowledge_sources"]],
        "source_edition_ids": [edition["id"] for edition in new_tables["knowledge_source_editions"]],
        "node_ids": [node["id"] for node in new_tables["knowledge_nodes"]],
        "node_relation_ids": [row["id"] for row in new_tables["knowledge_node_relations"]],
        "relation_ids": [row["id"] for row in new_tables["knowledge_relations"]],
        "evidence_ids": [row["id"] for row in new_tables["knowledge_evidence_items"]],
        "claim_ids": [row["id"] for row in new_tables["knowledge_claims"]],
        "claim_evidence_link_ids": [row["id"] for row in new_tables["knowledge_claim_evidence_links"]],
        "card_ids": [row["id"] for row in new_tables["knowledge_cards"]],
        "revision_ids": [
            *[row["id"] for row in new_tables["knowledge_claim_revisions"]],
            *[row["id"] for row in new_tables["knowledge_evidence_revisions"]],
            *[row["id"] for row in new_tables["knowledge_object_revisions"]],
        ],
    }
    for table_name, rows in new_tables.items():
        if table_name == "knowledge_version_snapshots":
            continue
        tables[table_name].extend(rows)
        tables[table_name].sort(key=_row_sort_key)

    snapshot_row = {
        "version_id": VERSION,
        "status": "published",
        "source_ids": sorted({*v51_snap["source_ids"], *new_ids["source_ids"]}),
        "source_edition_ids": sorted({*v51_snap["source_edition_ids"], *new_ids["source_edition_ids"]}),
        "node_ids": sorted({*v51_snap["node_ids"], *new_ids["node_ids"]}),
        "node_relation_ids": sorted({*v51_snap["node_relation_ids"], *new_ids["node_relation_ids"]}),
        "relation_ids": sorted({*v51_snap["relation_ids"], *new_ids["relation_ids"]}),
        "evidence_ids": sorted({*v51_snap["evidence_ids"], *new_ids["evidence_ids"]}),
        "claim_ids": sorted({*v51_snap["claim_ids"], *new_ids["claim_ids"]}),
        "claim_evidence_link_ids": sorted(
            {*v51_snap["claim_evidence_link_ids"], *new_ids["claim_evidence_link_ids"]}
        ),
        "card_ids": sorted({*v51_snap["card_ids"], *new_ids["card_ids"]}),
        "revision_ids": sorted({*v51_snap["revision_ids"], *new_ids["revision_ids"]}),
        "created_at": PUBLISHED_AT,
        "updated_at": PUBLISHED_AT,
    }
    tables["knowledge_version_snapshots"].append(snapshot_row)
    tables["knowledge_version_snapshots"].sort(key=_row_sort_key)

    return {
        "format": base["format"],
        "version": VERSION,
        "status": "published",
        "published_at": PUBLISHED_AT,
        "counts": {name: len(rows) for name, rows in tables.items()},
        "snapshot_counts": {
            "source_count": len(snapshot_row["source_ids"]),
            "source_edition_count": len(snapshot_row["source_edition_ids"]),
            "node_count": len(snapshot_row["node_ids"]),
            "node_relation_count": len(snapshot_row["node_relation_ids"]),
            "relation_count": len(snapshot_row["relation_ids"]),
            "evidence_count": len(snapshot_row["evidence_ids"]),
            "claim_count": len(snapshot_row["claim_ids"]),
            "claim_evidence_link_count": len(snapshot_row["claim_evidence_link_ids"]),
            "card_count": len(snapshot_row["card_ids"]),
            "revision_count": len(snapshot_row["revision_ids"]),
        },
        "tables": tables,
    }
